### ISSUE TITLE
Inconsistent user table column names

### ISSUE THREAD

**Issue by mihan007** [clevertech/YiiBoilerplate#10]
It isn't good idea to mix camelCase (passwordStrategy) and snake_case (login_attempts) across one table and even one database. We should rename it to snake_case and change codebase that using it. Do you agree?

**Comment by tonydspaniard** [comment]
I agree Mikhail, we have to modify those attributes that are in use for APasswordStrategy component.

**Comment by mtabin** [comment]
I agree

On Tuesday, September 4, 2012, Mikhail Kuklin wrote:

> It isn't good idea to mix camelCase (passwordStrategy) and snake_case
> (login_attempts) across one table and even one database. We should rename
> it to snake_case and change codebase that using it. Do you agree?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/clevertech/YiiBoilerplate/issues/10.

## 

Matt Tabin
Vice President
matt@clevertech.biz
Office: 347-850-7607
Mobile: 336-681-6114
www.clevertech.biz
Well-built beautifully designed web applications
Launch a minimal viable product in 30-90 days. Our deck: http://goo.gl/eWNsr

http://twitter.com/CleverIsbetter

**Comment by danielbehrendt** [comment]
Why snake_case? I prefer the camelCase way!

**Comment by resurtm** [comment]
@bitmatix, `snake_case` is prefered to use in table names and in table columns, because it's more portable across different RDBMSes (some of them are case insensitive regarding names).

Guide note ( http://www.yiiframework.com/doc/guide/1.1/en/database.ar ):

> Info: In this guide, we use lower case for all table names and column names. This is because different DBMS handle case-sensitivity differently. For example, PostgreSQL treats column names as case-insensitive by default, and we must quote a column in a query condition if the column contains mixed-case letters. Using lower case would help eliminate this problem.

**Comment by danielbehrendt** [comment]
@resurtm thank you for your fast reply and the explanation. I've seen that in the yii docs already but always prefered the camelCase. Maybe it's time for me to change :-) 

But I don't like the snake_case anyway...
