### ISSUE TITLE
I got error Property "GiiModule.generatorsPath" is not defined. when using gii first time

### ISSUE THREAD

**Issue by ceceps** [clevertech/YiiBoilerplate#17]
I Install YiiBoilerplate recent repostory, I set up all that describe on page, using YiiBolierplate and YiiBoostrap,  when using gii it got error like this :

Property "GiiModule.generatorsPath" is not defined. 

it erros on line added :

'generatorsPath' => array(
                'bootstrap.gii'
),
How tos solve this 

Thanks

**Comment by tonydspaniard** [comment]
Is not generatorsPath is generatorPaths, sorry for this typo bug. Will fix it asap

**Comment by tonydspaniard** [comment]
Wait a minute, you said Yii-Bootstrap? YiiBooster is included within the boilerplate, you do not need Yii-Bootstrap at all.

**Comment by tonydspaniard** [comment]
Can  you point to the line where YiiBoilerplate has that issue please?

**Comment by ceceps** [comment]
Yes,it was wrong typo that you explain on install guide on your web, it wrote "generatorsPath"  not "generatorPaths" on /config/main.php   on gii configuration. So Case Closed
