### ISSUE TITLE
Property "TbDataColumn.filterHtmlOptions" is not defined. on CRUD that generate from Bootstrap Generator 

### ISSUE THREAD

**Issue by ceceps** [clevertech/YiiBoilerplate#18]
I want tu use CRUD using Boostrap Generator, First I create Model ID then using Bootstrap Generator On Left Menu I Fill Model ID and Controller Id, generate and Success, but when I click manaage to display list Data, it got error below:

Property "TbDataColumn.filterHtmlOptions" is not defined. 

on line : 54

E:\xampp\htdocs\cashier\protected\extensions\bootstrap\widgets\TbDataColumn.php(54)

How To Solve this?

**Comment by tonydspaniard** [comment]
Please, update your Yii framework version...

**Comment by ceceps** [comment]
Ok Thanks previous it Yii, 1.1.10 now with upgraded to Yii.1.1.12 it was solve
