### ISSUE TITLE
Problem with CCookieCollection::add in Yii v1.1.11

### ISSUE THREAD

**Issue by MitraX** [clevertech/YiiBoilerplate#19]
Current YiiBoilerplate version contains Yii framework v1.1.11. It should be upgraded to v1.1.12 because the previous Yii version has a problem with CCookieCollection displaying error message:

"Declaration of CCookieCollection::add() should be compatible with that of CMap::add()"

The issue is fixed in v1.1.12: https://github.com/yiisoft/yii/pull/1091

**Comment by tonydspaniard** [comment]
Yii updated to v1.1.12, thanks MitraX!
