### ISSUE TITLE
admin advance search issue

### ISSUE THREAD

**Issue by shaan360** [clevertech/YiiBoilerplate#22]
the advance search is not working  for gii generated fields using this structure seems not working . please verify it

**Comment by tonydspaniard** [comment]
it was an issue with the 'buttonType', new coming version of YiiBooster will solve the issue. You could also do it by adding <code>'buttonType'=>'submit',</code> on https://github.com/clevertech/YiiBoilerplate/blob/master/common/extensions/bootstrap/gii/bootstrap/templates/default/_search.php#L23
