### ISSUE TITLE
Wrong placement of cache and contentCache Components configuration

### ISSUE THREAD

**Issue by suralc** [clevertech/YiiBoilerplate#23]
Currently the cache and contentCache entrys are placed after the components array leading to an unexpected failure (CModule: cache is readonly).

They should be placed inside the components array to work "out of box":

Ex:
https://github.com/clevertech/YiiBoilerplate/blob/master/backend/config/main.php#L104

Same goes for frontend.

Would do it myself, but I don't have git aviable right now.

**Comment by tonydspaniard** [comment]
You are right suralc... fixing it right now

**Comment by tonydspaniard** [comment]
done... thank you
