### ISSUE TITLE
NewPassword in User model

### ISSUE THREAD

**Issue by rinatio** [clevertech/YiiBoilerplate#24]
NewPassword in User model doesn't make sence and confuse. APasswordBehavior does all the job on update.

**Comment by rinatio** [comment]
Sorry, my fault. It still make sence on update, but compare rule set to all scenarios. Maybe it should be this way:

```
array('passwordConfirm', 'compare', 'compareAttribute' => 'newPassword', 'message' => Yii::t('validation', "Passwords don't match"), 'on' => 'update'),
array('passwordConfirm', 'compare', 'compareAttribute' => 'password', 'message' => Yii::t('validation', "Passwords don't match"), 'on' => 'insert'),
```

**Comment by tonydspaniard** [comment]
exactly... that is the reason why i have newPassword and confirmPassword... IMHO is much easier as if you set a value to password, the behavior will create new one asap...

**Comment by rinatio** [comment]
It looks like half done, validation and property is there, but there is no mention that old password is needed on update, there is no actual password update. Just property and rule ... Weird and confusing ...
