### ISSUE TITLE
Migrations shouldn't use models.

### ISSUE THREAD

**Issue by rinatio** [clevertech/YiiBoilerplate#25]
User table migration utilize User mode. Bad practice ...

**Comment by tonydspaniard** [comment]
Models are there to insert demo users for testing, and also is a prove of concept that the models + password encryption works

**Comment by rinatio** [comment]
You can insert them with `$this->insert`. Prove of concept is not enough price for bad practice. People will use this and later on they will change model validation, rename/delete property/column and migration won't work for new users/servers.
