### ISSUE TITLE
User.username lower case

### ISSUE THREAD

**Issue by rinatio** [clevertech/YiiBoilerplate#26]
Can we remove [strtolower](https://github.com/clevertech/YiiBoilerplate/blob/master/common/models/User.php#L165) User.username?

**Comment by tonydspaniard** [comment]
should we? as it will always depend on how you setup your database

**Comment by rinatio** [comment]
What do you mean? Why do we need it? Case insensitive mysql ?

**Comment by mtabin** [comment]
+1 for why do we need it? It is better to compare case to case... no?
