### ISSUE TITLE
Log on social networks

### ISSUE THREAD

**Issue by rmrevin** [clevertech/YiiBoilerplate#28]
Good afternoon. It would be great to add functionality to authenticate via social networks. For example you can easily integrate the service [ulogin](http://ulogin.ru/). Of course it ties the implementation of an external service, but this is the simplest solution.

Regards, Roman.

**Comment by resurtm** [comment]
There is existing native Yii extension: https://github.com/Nodge/yii-eauth
I think it's far better way of adding such feature.

**Comment by rmrevin** [comment]
No matter what solution is used. I beg to implement functionality.

**Comment by tonydspaniard** [comment]
It could a great feature but is a bit off the solution provided... maybe I consider that on [YiiBooster](http://github.com/clevertech/yiibooster) but not on the boilerplate.
