### ISSUE TITLE
I think in .htaccess frontend mistake

### ISSUE THREAD

**Issue by rmrevin** [clevertech/YiiBoilerplate#29]
I have a standard CentOS 6 not start frontend.

``` bash
[revin@07701 www]$ uname -a
Linux 07701.corp 2.6.32-279.5.2.el6.x86_64 #1 SMP Fri Aug 24 01:07:11 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
[revin@07701 www]$ httpd -v
Server version: Apache/2.2.15 (Unix)
Server built:   Feb 13 2012 22:31:42
```

If any more information on the configuration needed, I can provide. All basic modules of apache installed. If file .htaccess remove, frontend running.

**Comment by tonydspaniard** [comment]
Thats strange... could you please provide that info? Thanks

**Comment by rmrevin** [comment]
What kind of information?

**Comment by rinatio** [comment]
I updated `.htaccess` files to the [h5bp](https://github.com/h5bp/html5-boilerplate) v4.2.0. Let us know if you still have an issue. Thanks!
