### ISSUE TITLE
Может не корректно работать аутентификация

### ISSUE THREAD

**Issue by vjik** [clevertech/YiiBoilerplate#3]
https://github.com/clevertech/YiiBoilerplate/blob/master/frontend/components/UserIdentity.php#L24

Если **username** будет содержать символ **@**, то будет поиск по email, что не корректно в данном случае.
Получается надо делать проверку, чтобы **username** не содержал собаки.

**Comment by rinatio** [comment]
Could you please use English language, since most of developers are not speeking Russian. Thanks.

**Comment by tonydspaniard** [comment]
It is true that if we have two different emails in two different places it wont work as expected but normally applications wont allow the use of '@' on the username. Maybe we should consider the idea of including that rule in the user model. What do you think?
