### ISSUE TITLE
ENH suggestion : More config options on Actions button in Box Widget

### ISSUE THREAD

**Issue by fleuryc** [clevertech/YiiBoilerplate#32]
Just a enhancement suggestion : The new Box widget is great, it would be nice to be able to customize the Actions button more though. 
Llike the type of the button, maybe let the choice between simple button, button group or button dropdown...

Thanks for all your contribution!

**Comment by fleuryc** [comment]
Ooops, I meant to create this issue in the YiiBooster repo...

**Comment by tonydspaniard** [comment]
No @fleuryc , in fact, there is a new improvement ( you can add different types of buttons now )

**Comment by fleuryc** [comment]
Awesome!
