### ISSUE TITLE
URL rules not working

### ISSUE THREAD

**Issue by rsn86** [clevertech/YiiBoilerplate#36]
Hi,

I've cloned github repo inside my webroot dir (apache mod_rewrite enabled), Set RewriteBase to /YiiBoilerplate/backend/www (backend's .htaccess) Browsed http://localhost/YiiBoilerplate/backend/www and when i click on links about, contact or login i get a 404 error

http://localhost/YiiBoilerplate/backend/www/site/page/?view=about http://localhost/YiiBoilerplate/backend/www/site/contact/ http://localhost/YiiBoilerplate/backend/www/site/login/

What I'm missing?

Regards, Rodrigo

**Comment by sallespromanager** [comment]
Hi Rodrigo,

I had the same issue and after setting the RewriteBase in backend/www .htaccess  If you are in a sub folder of your web root, it did work.

Antonio, i suggest to make the initial configuration Wiki much less verbose and please make sure this .htaccess RewriteBase comment on it. 

I was installing Boilerplate to use Yii-SES and it was very hard to get to this point.

Thanks for your excellent work in all Yii extensions !

[]'s Rafael

**Comment by rsn86** [comment]
Hi Rafael,

Yassen solved my problem, take a look at:
http://www.yiiframework.com/wiki/374/yiiboilerplate-setup-a-professional-project-structure-in-seconds/#c11366

You must enable "AllowOverride All" for the www directories (backend, frontend, ...) in apache config

Regards,
Rodrigo

**Comment by leo4all** [comment]
Having same issue, 

.htaccess
allow from all

RewriteBase /home/content/a/f/c/afc/html/folder/backend/www

Still doesnt work.

**Comment by rsn86** [comment]
leo4all

Assuming you are using Apache, on apache's config you should enable "AllowOverride All" for your www directories

Something like this:

<Directory /home/content/a/f/c/afc/html/folder/backend/www>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
</Directory>
