### ISSUE TITLE
Initial sql dump for user table

### ISSUE THREAD

**Issue by meliborn** [clevertech/YiiBoilerplate#37]
I see, that user model implements non standart yii user table. Where I can find initial dump for it?

**Comment by pythagor** [comment]
I'm not sure maybe over there https://github.com/clevertech/YiiBoilerplate/blob/master/console/migrations/m120805_131754_user_table_migration.php

**Comment by meliborn** [comment]
Sorry, already found it.

**Comment by leo4all** [comment]
how can I implement the migrations manually?
