### ISSUE TITLE
Explain VCS for the YiiBoilerplate in the README

### ISSUE THREAD

**Issue by tom--** [clevertech/YiiBoilerplate#39]
This is a really nice organization of a Yii project and your solutions for handling configurations are particularly helpful.

But it's not obvious to me how users might keep up2date with clevertech/YiiBoilerplate as an upstream. Can you make suggestions in the README?

**Comment by tonydspaniard** [comment]
WIll do @tom-- in fact we should keep VCS wip as we do with booster, hope i have some time this weekend to update both site booster and boilerplate with new versions

**Comment by hijarian** [comment]
@tom-- YiiBoilerplate is neither the library nor a framework. It's a starting point of the application. Forget about the updates of it, because after ~6 months of developing your YiiBoilerplate-based application there will be not much of initial content anyway.
