### ISSUE TITLE
Assests publishing error.

### ISSUE THREAD

**Issue by thiagovidal** [clevertech/YiiBoilerplate#48]
Anyone having assets publishing errors?

**Comment by luizmcarvalho** [comment]
Did you remember to run the script runpostdeploy?

Luiz Fernando M. de Carvalho
Belo Horizonte - MG

2013/1/31 thiagovidal notifications@github.com

**Comment by thiagovidal** [comment]
Yeah dude. Actually I working with this application scheme for the past three months.

Pt_br
Então Luiz... Eu não sei se é um problema do meu pc... estou usando essa joça do Windows 8 com Xampp (ultima versão)... Ta tudo meio estranho... Meu note antigo quebrou e comprei outro... pra não usar um p$#ata eu fiquei com o que veio no pc... Acho que pode ser isso.

**Comment by rinatio** [comment]
Check if assets directories exist and have correct permissions on your setup, otherwise please provide more info. Thanks.
