### ISSUE TITLE
Gii Module

### ISSUE THREAD

**Issue by gakker** [clevertech/YiiBoilerplate#49]
Hello im trying to make a new model and for that i need gii.

at the moment it doesnt open like this.

http://localhost/mysite/backend/gii

i have uncommented gii module in main.php residing in backend/config folder.

the DB credentials are provided in common/config though since db will be shared by both frontend and backend.

**Comment by araminder** [comment]
I am not sure if you still have this issue but here is my solution. 
apache vhosts file

NameVirtualHost 127.0.0.1:80
<VirtualHost 127.0.0.1:80> 
    DocumentRoot "C:/Projects/phpstorm/YiiBoilerplate/backend/www"
    ServerName backend.YiiBoilerplate.jet
    ErrorLog "logs/YiiBoilerplate-error.log"
    CustomLog "logs/YiiBoilerplate-access.log" common
</VirtualHost>

<VirtualHost 127.0.0.1:80>
     DocumentRoot "C:/Projects/phpstorm/YiiBoilerplate/frontend/www"
    ServerName YiiBoilerplate.jet
    ErrorLog "logs/YiiBoilerplate-error.log"
    CustomLog "logs/YiiBoilerplate-access.log" common
</VirtualHost>

and 'hosts' file has following entries
    127.0.0.1       YiiBoilerplate.jet
    127.0.0.1       backend.YiiBoilerplate.jet

after setting up like above I can go to gii by using http://backend.yiiboilerplate.jet/gii

**Comment by rinatio** [comment]
You have to point your local webserver to the `backend/www` directory and then it should be working alright. Let us know if you still have an issues. Thanks
