### ISSUE TITLE
В моделе USER отдаётся не правильное имя таблицы

### ISSUE THREAD

**Issue by vjik** [clevertech/YiiBoilerplate#5]
https://github.com/clevertech/YiiBoilerplate/blob/master/common/models/User.php#L59

Если будут использоваться префиксы у таблиц в БД, то метод отдаст не правильное имя таблицы. Надо фигурные скобки добавить.

**Comment by tonydspaniard** [comment]
Using table prefixes {{user}} slows down a little bit the application and also the migration has a 'user' table not a 'tbl_user'.

PS: I am not very good with russian nor google :) please post the issues in english if you can. Thanks!
