### ISSUE TITLE
google chart cannot open

### ISSUE THREAD

**Issue by elviskudo** [clevertech/YiiBoilerplate#52]
Hi,

i got some problem with google chart visualize, when i add to render partial, chart is not showed up, how come?

any solution?

thanks, and sorry my english is bad

**Comment by hijarian** [comment]
It is not YiiBooster issues tracker. YiiBoilerplate is a separate, completely different project.

Most possibly you were rendering that partial with `TbGoogleVisualizationChart` without scripts and styles supporting it. Just a HTML is useless for this widget.
