### ISSUE TITLE
frontend not working.

### ISSUE THREAD

**Issue by hemc4** [clevertech/YiiBoilerplate#55]
I have created two virtual host in my windows machine. 
www.yiibi.com and
www.admin.yiibi.com

configuration is following 

<pre>
<VirtualHost *:80>
    ServerAdmin webmaster@yiibi.com
    DocumentRoot "C:/xampp/htdocs/YiiBoilerplate/frontend/www"
    ServerName www.yiibi.com
   <Directory "C:/xampp/htdocs/YiiBoilerplate/frontend/www/">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order Allow,Deny
        Allow From All
        </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@yiibi.com
    DocumentRoot "C:/xampp/htdocs/YiiBoilerplate/backend/www"
    ServerName www.admin.yiibi.com
   <Directory "C:/xampp/htdocs/YiiBoilerplate/backend/www/">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order Allow,Deny
        Allow From All
        </Directory>
</VirtualHost>

</pre>

Backend is working alright but fronted is not working.

**Comment by lrcg** [comment]
Frontend or backend? Title says front, comments say back.

Default frontend contains just one line in `index.php`: _This is index view file..._.

**Comment by hemc4** [comment]
I have change the virtual host to
yiibi.com and
www.admin.yiibi.com
Now it is working.But how to make it working for 
www.yiibi.com and 
admin.yiibi.com

**Comment by lrcg** [comment]
Your problem is with your server config, not Yii.

**Comment by hemc4** [comment]
Yeah

**Comment by vinitchoudhari** [comment]
BOILERPLATE frontend gives everytime ERROR 404

WHEN I AM PUTTING http://localhost/PROJECT NAME/frontend/www/

there is any setting for base url ?...because in console it shows error http://localhost/site/isLogged not found.

actually it not get the PROJECT NAME after localhost...

pls help..

**Comment by lrcg** [comment]
Set your document root to `wherever/PROJECT NAME/frontend/www` in your HTTP server config.

**Comment by vinitchoudhari** [comment]
i set baseUrl in config of fronted but still not working...

**Comment by vinitchoudhari** [comment]
in `session.js`

``` javascript
 var authUri = '/site/isLogged';
 return {
    /**
     * Checks whether is logged in or not
     * @return {Boolean}
     */
    checkAuth: function (callback) {
        $.when($.ajax(authUri)).then(callback);
    }
    };
```

and `authUri` only contain `'/site/isLogged'` how to append base url in `session.js`

**Comment by lrcg** [comment]
These are not bugs, but errors in your configuration. Please ask the questions [here](http://www.yiiframework.com/wiki/374/yiiboilerplate-setup-a-professional-project-structure-in-seconds/) or [here](http://www.yiiframework.com/community/).
