### ISSUE TITLE
frontend (etc) config dirs does not override common config

### ISSUE THREAD

**Issue by iplus** [clevertech/YiiBoilerplate#6]
https://github.com/clevertech/YiiBoilerplate/blob/master/frontend/config/main.php#L15

on this line variable `$currentDir` is overrided to `"....common/config"`, beceause of requiring `params.php` and on line 23 wrong value is used, so `main-local.php` etc files are included not from current dir, but from common dir.

**Comment by tonydspaniard** [comment]
You are right, we will remove the use of $currentDir variables to avoid such issue.

**Comment by tonydspaniard** [comment]
Fixed on https://github.com/clevertech/YiiBoilerplate/commit/8bc3785c93418f273dabcf709b86ce9551ad6b5e
