### ISSUE TITLE
.htaccess lost POST when suppress or force the "www." at the beginning of URLs 

### ISSUE THREAD

**Issue by doucreator** [clevertech/YiiBoilerplate#61]
These rules are the reason that the lost data sent via POST
<IfModule mod_rewrite.c>
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} ^www.(.+)$ [NC]
  RewriteRule ^ http://%1%{REQUEST_URI} [R=301,L]
</IfModule>

To avoid this, I added the rules

<IfModule mod_rewrite.c>
  RewriteCond %{REQUEST_METHOD}  !=POST
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} ^www.(.+)$ [NC]
  RewriteRule ^ http://%1%{REQUEST_URI} [R=301,L]
</IfModule>

**Comment by rinatio** [comment]
`.htaccess` was updated to the latest [h5pb](https://github.com/h5bp/html5-boilerplate) v4.2.0. You can always disable those rewrite rules, if you don't need them. Let us know if you still have an issues.
