### ISSUE TITLE
Unable to find the requested action "view" on backend/www/index

### ISSUE THREAD

**Issue by zsiddiqi** [clevertech/YiiBoilerplate#62]
Hi,

I am working with the latest github version 7d2ef07af5 of this script. Once the default app is setup and working, I am trying to test the actions on the index.php for the default table. 

Clicking on any of them doesn't work and leads me to the response page displaying Error 404 The system is unable to find the requested action "view".

Tried searching forums, google etc. but cannot find any help on how to fix it. Any help is much appreciated.

HZ.

**Comment by rinatio** [comment]
@halisz that grid is just an example, you have to implement CRUD on your own.
