### ISSUE TITLE
Will the current YiiBooster v1.0.7 be included into Boilerplate?

### ISSUE THREAD

**Issue by gb5256** [clevertech/YiiBoilerplate#64]
Hello out there, 
I am a very happy user of the boilerplate.
I just realized that the current version of Booster is 1.0.7 while the one included in the boilerplate is 1.0.4.
I just tried to update the my 1.04 folders with 1.0.7 but this is breaking a lot of things.

Did anybody manage to update?
Is this necessary at all?

gb5256

**Comment by hijarian** [comment]
Latest master, which eventually become 1.0.0 release, will include latest master of YiiBooster, installable by Composer, so you're able to specify whatever version you want.
