### ISSUE TITLE
Issue using an CActiveDataProvider with a non standard Key together with TBRelationalColumn

### ISSUE THREAD

**Issue by coupej** [clevertech/YiiBoilerplate#66]
I think i discovered an issue in the TBRelationalColumn getPrimaryKey method. 

When feeding the RBRelationalColumn with a dataProvider where the keyAttribute !== null the widget crashes with a TbRelationalColumn.keyAttribute is not defined error. 

I tracked the bug down to the following line 
...

```
        $key = $this->grid->dataProvider->keyAttribute === null ? $data->getPrimaryKey()
            : $data->{$this->keyAttribute};
```

...

Where you can see the keyAttribute of the $this object is returned instead of the keyAttribute of the dataProvider. 

so this 
...

```
        $key = $this->grid->dataProvider->keyAttribute === null ? $data->getPrimaryKey()
            : $data->{$this->grid->dataProvider->keyAttribute};
```

...

should fix the problem. 

Best regards

**Comment by pawl** [comment]
Good fix.

I also had to change line 316 in tbExtendedGridView to get keyAttribute from cActiveDataProvider working:

From this:
            $key = $this->dataProvider->keyAttribute === null ? $data->getPrimaryKey() : $data->{$this->keyAttribute};

To this:
            $key = $this->dataProvider->keyAttribute === null ? $data->getPrimaryKey() : $data->{$this->dataProvider->keyAttribute};

**Comment by hijarian** [comment]
This issue is for YiiBooster, completely different, albeit related, project.
