### ISSUE TITLE
runpostdeploy doesn't work on Windows

### ISSUE THREAD

**Issue by nothing083** [clevertech/YiiBoilerplate#69]
Hi,

I tried to run runpostdeploy.bat and got this error:
"Could not open input file: E:\xampp\htdocs\yiiboiler\common\lib\postdeploy.php"

Could you please have a check?

Thanks

**Comment by IStranger** [comment]
Indeed, I finally decided to try this project, but I can't run my first application. I too am getting this error.

**Comment by hijarian** [comment]
Latest master does not have the `runpostdeploy` script as it's unnecessary.

To prepare your app without the Vagrant, in hard, manual, way you need to:
1. Create a MySQL database
2. Copy a file `common/config/overrides/local.example.php` to `common/config/overrides/local.php` and fill in the database access configuration here.
3. Run the `php composer.phar install` from the root of codebase.
4. Run the `bin/yiic migrate` script.
5. Publish the `frontend/www` and `backend/www` as separate virtual domains.
6. Also create all needed runtime directories: `frontend/runtime`, `frontend/runtime/app_logs`, `frontend/www/assets`, `backend/runtime`, `backend/runtime/app_logs`, `backend/www/assets`.

The exact things to do are described in `carcass/vagrant/setup-app.sh`.

Easy way is

```
vagrant up
```

given you have Vagrant and Virtualbox installed.
