### ISSUE TITLE
it would be nice also include API

### ISSUE THREAD

**Issue by plandem** [clevertech/YiiBoilerplate#70]
like at Initializer, because sometimes you need to create API too, it has same config mostly, but quite differ php files, include www.

Anyway, thanks for update.

**Comment by plandem** [comment]
i mean 'API' application. So we would have next root folders: api, backend, common, console, frontend

**Comment by hijarian** [comment]
I can imagine the `mobile` entry point also. It was considered before, but the decision was to make just a barebone boilerplate with only the crucial stuff. We cannot satisfy anyone and that was not our goal.

It's relatively easy to add another entry point to your system, it's basically just another directory, config builder copypasted from, say, `backend`, and the `index.php` entry point script.

YiiBoilerplate design is that you grab it and start building and reconstructing it to the shape _you_ want. So, no neither `api` nor `mobile` entry points by default.
