### ISSUE TITLE
Timeout 300s #SOLVED

### ISSUE THREAD

**Issue by infoitservit** [clevertech/YiiBoilerplate#72]
During the vagrant up process someone could face this problem...

![image](https://f.cloud.github.com/assets/3064689/1832423/c7a0d43e-73b3-11e3-8fa9-47a0060d2fad.png)

If i try to execute COMPOSER_PROCESS_TIMEOUT=2000 php composer.phar install, i get an error on windows, cause it doesn't recognize the "COMPOSER_PROCESS_TIMEOUT=2000" instruction.

There is a way to do it on windows and through windows shell?

If i install composer on the vagrant instance (vagrant ssh) and then execute that statement, it works correctly.
# SOLVED

Just use "php composer.phar install --prefer-dist". Composer gets zipped distributions, so waste less time to download them.

**Comment by suralc** [comment]
@infoitservit 

On windows 
`set` or `setx` could solve your problem. 

http://ss64.com/nt/set.html
http://ss64.com/nt/setx.html
