### ISSUE TITLE
Issue syntax error

### ISSUE THREAD

**Issue by gplaza** [clevertech/YiiBoilerplate#76]
Hi,

i have an issue with a very basic setup :
- yii framework is in [root_folder]/vendor/yiisoft/yii/framework/
- i have renamed all the local.example.php in all config : common, backend, frontend, console
- I use a mysql BDD like the initial setup (boilerplate/boilerplate/boilerplate)

But i have this error :

Parse error: syntax error, unexpected '[' in /home/gilles/workspace/boilerplate/common/config/overrides/base.php on line 5 Call Stack: 0.0003 644448 1. {main}() /home/gilles/workspace/boilerplate/frontend/www/index.php:0 0.0261 2201016 2. YiiBase::createApplication() /home/gilles/workspace/boilerplate/frontend/www/index.php:23 0.0261 2209168 3. CApplication->__construct() /home/gilles/workspace/boilerplate/vendor/yiisoft/yii/framework/YiiBase.php:125 0.0264 2217424 4. require('/home/gilles/workspace/boilerplate/frontend/config/main.php') /home/gilles/workspace/boilerplate/vendor/yiisoft/yii/framework/base/CApplication.php:133 0.0274 2331336 5. require('/home/gilles/workspace/boilerplate/common/config/main.php') /home/gilles/workspace/boilerplate/frontend/config/main.php:12 

the indentation and syntax seen correct in the file /common/config/overrides/base.php

**Comment by SilverFire** [comment]
Hello. What version of PHP are you using? It shall be 5.4±

**Comment by gplaza** [comment]
Yes ! You are quite right ! (i have the php 5.3....)
Sorry for this issue .... :(
