### ISSUE TITLE
Application DATA directory

### ISSUE THREAD

**Issue by vitalets** [clevertech/YiiBoilerplate#8]
Nice project!
My question is about <code>data</code> directory that is used for storing information, specific for environment (e.g user uploaded files, generated reports etc).
This directory is not under version control.
how do you arrange it in your structure?

**Comment by tonydspaniard** [comment]
Every project requires to store different data in different places and I wasn't sure were to put it. 

You should check https://github.com/tonydspaniard/YiiBootstrap which is a clone of Chris' excelent YiiBootstrap with new features that we are about to release and include to the boilerplate. One of the components that we are going to include is a resource manager, a component that a developer would be able to configure the path to upload/view data, whether is in a writable folder or a DB or even Yii's runtime folder.

**Comment by suralc** [comment]
Are you going to update the YiiBootstrap repository with the latest changes made in the original hg-repository? Because I like what I've seen so far and it would be nice to simply add it as a submodule instead of  more or less failprone way to use mercurial in a git-repository.

**Comment by tonydspaniard** [comment]
The bootstrap that will be updated with is from https://github.com/tonydspaniard/YiiBootstrap 

We will soon update it with a proper wiki.

Enviado desde mi BlackBerry® de Vodafone

-----Original Message-----

**Comment by tonydspaniard** [comment]
The boilerplate has been updated to use [YiiBooster](http://yii-booster.clevertech.biz). To solve the issue with the 'data' (resources) I am planning to create a component that will work specifically to handle pushed/pulled resources (images-files-etc). I am closing this issue till then.
