### ISSUE TITLE
Code Generator - gii

### ISSUE THREAD

**Issue by iloveyii** [clevertech/YiiBoilerplate#85]
How can we use gii in this boilerplate?

**Comment by hijarian** [comment]
Each entry point (`frontend`, `backend`, `console`) is a separate Yii application with its own config.

Just put the required Gii module declaration inside the configuration of the entry point you want. 

More than that, `backend/config/overrides/local.example.php` already contains the declaration for Gii, so backend already has Gii enabled, provided you use the `local.example.php` as a basis for your `local.php`.

**Comment by hijarian** [comment]
As a side note: please, do not put Gii module declaration into anything other than your local config, Gii is a potential security breach.
